// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQH8cMfpZX_-Hl3nyl_EWuvotng9nQQr0',
    appId: '1:1019239578712:web:9cbbac40f1d485d6479e2d',
    messagingSenderId: '1019239578712',
    projectId: 'assignment5-6f17f',
    authDomain: 'assignment5-6f17f.firebaseapp.com',
    storageBucket: 'assignment5-6f17f.firebasestorage.app',
    measurementId: 'G-DF4ZJ94QM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHIF-V_rHBnNb0oexgmFSCgZ0IuGoRWPg',
    appId: '1:1019239578712:android:5af139c0b26a4d13479e2d',
    messagingSenderId: '1019239578712',
    projectId: 'assignment5-6f17f',
    storageBucket: 'assignment5-6f17f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUxt3qFQAU3mROqYJ26LVJtsKnLdGaZ-I',
    appId: '1:1019239578712:ios:a2b4794c2845e93b479e2d',
    messagingSenderId: '1019239578712',
    projectId: 'assignment5-6f17f',
    storageBucket: 'assignment5-6f17f.firebasestorage.app',
    iosBundleId: 'com.example.assignment5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUxt3qFQAU3mROqYJ26LVJtsKnLdGaZ-I',
    appId: '1:1019239578712:ios:a2b4794c2845e93b479e2d',
    messagingSenderId: '1019239578712',
    projectId: 'assignment5-6f17f',
    storageBucket: 'assignment5-6f17f.firebasestorage.app',
    iosBundleId: 'com.example.assignment5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQH8cMfpZX_-Hl3nyl_EWuvotng9nQQr0',
    appId: '1:1019239578712:web:5b98a7298cbd3fb3479e2d',
    messagingSenderId: '1019239578712',
    projectId: 'assignment5-6f17f',
    authDomain: 'assignment5-6f17f.firebaseapp.com',
    storageBucket: 'assignment5-6f17f.firebasestorage.app',
    measurementId: 'G-LK4J86HN9Q',
  );
}
